version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-deps:
        dependency-type: production
      development-deps:
        dependency-type: development
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - dependencies
      - ci

  - package-ecosystem: pub
    directory: "/apps/mobile"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - dependencies
      - mobile

  - package-ecosystem: cargo
    directory: "/apps/desktop/src-tauri"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - dependencies
      - desktop
